"use client";

import { Zap, TrendingUp, TrendingDown, Minus, Info } from "lucide-react";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

interface PredictedBottleneck {
  zone: string;
  eta_minutes: number;
  confidence: number;
  trend: "increasing" | "stable" | "decreasing";
  cascade_risk: "low" | "medium" | "high";
  recommended_action: string;
}

interface BottleneckCardProps {
  data: PredictedBottleneck | null;
}

export default function BottleneckCard({ data }: BottleneckCardProps) {
  if (!data) return null;

  const getTrendIcon = (trend: string) => {
    switch (trend) {
      case "increasing": return <TrendingUp className="w-3 h-3 text-red-500" />;
      case "decreasing": return <TrendingDown className="w-3 h-3 text-emerald-500" />;
      default: return <Minus className="w-3 h-3 text-white/40" />;
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case "high": return "text-red-500 bg-red-500/10 border-red-500/20";
      case "medium": return "text-amber-500 bg-amber-500/10 border-amber-500/20";
      default: return "text-emerald-500 bg-emerald-500/10 border-emerald-500/20";
    }
  };

  return (
    <div className="dashboard-card border-blue-500/20 bg-blue-500/[0.02] flex flex-col gap-5 animate-fade-in relative overflow-hidden">
      <div className="absolute -top-12 -right-12 w-32 h-32 bg-blue-500/10 blur-3xl rounded-full" />
      <div className="flex items-center justify-between relative">
        <div className="flex items-center gap-2 text-blue-400">
          <Zap className="w-4 h-4 fill-blue-400/20" />
          <h3 className="text-xs font-bold uppercase tracking-widest">Predictive Intelligence</h3>
        </div>
        <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-[10px] font-bold text-blue-400">
          {Math.round(data.confidence * 100)}% CONFIDENCE
        </div>
      </div>
      <div className="flex flex-col gap-1">
        <span className="text-4xl font-black tracking-tighter text-white">ZONE {data.zone}</span>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1 text-sm font-medium text-white/50">
            ETA <span className="text-white font-bold">{data.eta_minutes}m</span>
          </div>
          <div className="h-3 w-px bg-white/10" />
          <div className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-tighter">
            {getTrendIcon(data.trend)}
            <span className="text-white/60">{data.trend}</span>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div className={cn("flex flex-col gap-1 p-2 rounded-lg border", getRiskColor(data.cascade_risk))}>
          <span className="text-[9px] font-black uppercase tracking-widest opacity-60">Cascade Risk</span>
          <span className="text-xs font-bold uppercase">{data.cascade_risk}</span>
        </div>
        <div className="flex flex-col gap-1 p-2 rounded-lg border border-white/5 bg-white/[0.02]">
          <span className="text-[9px] font-black uppercase tracking-widest text-white/40">Action Suggested</span>
          <span className="text-xs font-bold text-white/80">{data.recommended_action}</span>
        </div>
      </div>
      <div className="flex items-start gap-2 text-[10px] text-white/30 italic leading-snug">
        <Info className="w-3 h-3 flex-shrink-0 mt-0.5" />
        <p>Prediction generated by the VenueIQ cascade engine based on current density trends and historical surges.</p>
      </div>
    </div>
  );
}
